name: Create GitHub Repository

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - feature

jobs:
  create_repo_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create GitHub repository
        run: |
          while IFS=' ' read -r project_name project_id; do
          token="${{ secrets.HUB_PERSONAL_ACCESS_TOKEN }}"
          PRIVATE_TOKEN="${{ secrets.GITLAB_TOKEN }}"
          #response=$(curl -X POST -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.v3+json" -d '{"name": "'"$project_name"'", "private": false}' https://api.github.com/user/repos)
          #response_code=$(curl -w "%{http_code}\n" -o response.json --request POST --header "PRIVATE-TOKEN:$PRIVATE_TOKEN" --header "Content-Type:application/json" --data '{"url":"https://n509249:'"$token"'@github.com/n509249/'"$project_name"'.git","enabled": true}'  https://gitlab.com/api/v4/projects/$project_id/remote_mirrors)
          response_code=$(curl -w "%{http_code}\n" -o response1.json --request POST --header "PRIVATE-TOKEN:$PRIVATE_TOKEN" --header "Content-Type:application/json" https://gitlab.com/api/v4/projects/$project_id/repository/branches?branch=feature/migration&ref=master)
          #curl --request POST --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" --data "branch_name=feature/migration" "https://gitlab.com/api/v4/projects/$project_id/repository/branches"
          done <project_name_url.txt
