name: Mirror GitLab to GitHub
on:
  push:
    branches:
      - feature

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create GitHub repository
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.HUB_TOKEN }}
          script: |
            PAT="YOUR_GITHUB_PERSONAL_ACCESS_TOKEN"
            REPO_NAME="POC-repo"
            ORG_NAME="n509249"           
            response=$(curl -X POST -H "Authorization: token $PAT" -H "Accept: application/vnd.github.v3+json" \
                       -d "{\"name\":\"$REPO_NAME\","private":false}" "https://api.github.com/user/repos")
          
            echo $response
