name: Create GitHub Repository

on:
  push:
    branches:
      - feature

jobs:
  create_repo_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create GitHub repository
      - env:
          GH_TOKEN: ${{ secrets.HUB_PERSONAL_ACCESS_TOKEN }}
        run: |
          #PAT= ${{ secrets.HUB_PERSONAL_ACCESS_TOKEN }}
          #REPO_NAME="new-repo-poc"
          #ORG_NAME="n509249"
          
          response=$(curl -X POST   -H "Authorization: Bearer ${{ secrets.HUB_PERSONAL_ACCESS_TOKEN }}"   -H "Accept: application/vnd.github.v3+json"   -d '{"name": "new-repo-name", "private": false}'   https://api.github.com/user/repos)
          
          echo $response
