name: Create GitHub Repository

on:
  push:
    branches:
      - feature

jobs:
  create_repo_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create GitHub repository
        run: |
          token="${{ secrets.HUB_PERSONAL_ACCESS_TOKEN }}"
          response=$(curl -X POST -H "Authorization: Bearer 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" -H "Accept: application/vnd.github.v3+json" -d '{"name": "new-repo-name", "private": false}' https://api.github.com/user/repos)
          echo "$response"
