name: Mirror GitLab to GitHub
on:
  push:
    branches:
      - feature  # Adjust the branch name as needed

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create GitHub repository
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            PAT="YOUR_GITHUB_PERSONAL_ACCESS_TOKEN"
            REPO_NAME="POC-repo"
            ORG_NAME="n509249"           
            response=$(curl -X POST -H "Authorization: token $PAT" -H "Accept: application/vnd.github.v3+json" \
                       -d "{\"name\":\"$REPO_NAME\","private":false}" "https://api.github.com/user/repos")
          
            echo $response
            
    #  - name: Mirror to GitHub repository
      #  run: |
       #   cd poc-dummy-interface.git
        #  git push --mirror https://github.com/n509249/new-github-repo.git
         # cd ..
          #rm -rf poc-dummy-interface.git
        #env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
